import streamlit as st
st.title("# VBA Resources")
st.sidebar.markdown("# VBA Resources")

text = """
# Personal Macros
This repo contains personal VBA macros and udfs I've created and collected over the years.
Direct download link: https://github.com/dbogt/vbaMacros/raw/main/Personal%20Macros.xlsm

# VBA Resources
Below is also a list of a few resources I've used in the past for VBA:
- **OzGrid** - a slightly older website, but they have a good repository of useful User Defined Functions: http://www.ozgrid.com/VBA/Functions.htm
- **SpreadSheetGuru** - a blog type site on Excel and VBA tricks; they have a good repository of VBA macros: https://www.thespreadsheetguru.com/the-code-vault
- **Chandoo** - another blog type site I follow; he also has some decent VBA macros: https://chandoo.org/wp/excel-vba/examples/

Other Finance related macros and UDFs:
- http://investexcel.net/portfolio-analysis-kb/
- http://investexcel.net/black-scholes-greeks-vba/
- https://www.jkp-ads.com/Download.asp
- https://www.optiontradingtips.com/pricing/black-and-scholes.html


**[Stack Overflow](https://stackoverflow.com/)**
- this is a great resource for finding solutions to typical problems; if you're trying to figure how to code something, someone has probably already thought about it before and asked on this forum; the answers are user-generated by other programmers, so be careful when you copy a solution from someone; usually, however, the answer voted as "best answer" is a clean, good version of the answer
- with the tools learned in our class, you will be able to "decode" whatever solution someone has posted - if you ever find a piece of code that you can't understand, shoot me an email and I could walk you through it

**[Excel At Finance](https://excelatfinance.com/contents/)**
- they have good examples of advanced excel concepts, and a whole section on VBA by topic as well

**Books** - if you do want to go the book route, I would recommend VBA For Modelers by S. Christian Albright. This is the textbook I used back in undergrad and it has a heavier focus on applications for Finance and Statistics. The author also has example excel files posted on his site.
"""
st.markdown(text)
